# Versione per produzione con database cloud

services:
  # Backend .NET
  backend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.backend
    container_name: videogames-backend-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_URL=${DATABASE_URL}
      - SteamApiKey=${STEAM_API_KEY}
    ports:
      - "5000:80"
    dns:
      - "8.8.8.8"
      - "1.1.1.1"
    networks:
      - videogames-network

  # Frontend React
  frontend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000
        - REACT_APP_VERSION=1.0.0
        - REACT_APP_ENV=production
    container_name: videogames-frontend-prod
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - videogames-network

networks:
  videogames-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
