# Versione per produzione con database cloud

services:
  # Backend .NET
  backend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.backend
    container_name: videogames-backend-prod
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      # Database connection string dal .env
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
      # Steam API Key dal .env della root (opzionale)
      - SteamApiKey=${STEAM_API_KEY}
    ports:
      - "5000:80"
    networks:
      - videogames-network

  # Frontend React
  frontend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000
        - REACT_APP_VERSION=1.0.0
        - REACT_APP_ENV=production    container_name: videogames-frontend-prod
    env_file:
      - frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - videogames-network

networks:
  videogames-network:
    driver: bridge
